### ISSUE TITLE
Support const generics in struct declarations

### ISSUE THREAD

**Issue by notgull** [taiki-e/pin-project-lite#82] opened 2024-03-13 05:47 UTC
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3e812874c31dbe9d6aecc9e91f04fe5c

It would be nice if `const` generics were supported in this crate as well.

**Comment by taiki-e** [comment] 2024-03-13 06:18
duplicate of #62

**Closed by taiki-e** 2024-03-13 06:18 UTC
